### ISSUE TITLE
Make an executable in put it in releases

### ISSUE THREAD

**Issue by sryu1** [rdinit/flightgear_discord_RPC#1]
Just a suggestion, make an executable file with pyinstaller (with --onefile) so that other people don't have to install python and stuff.

**Comment by sryu1** [comment]
I could do it for you if you give me collaboration permissions...

**Comment by rdinit** [comment]
Done!
Latest release: https://github.com/rdinit/flightgear_discord_RPC/releases/tag/v0.1.0
